[package]
name = "sound-effect-player"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.46", features = ["derive"] }
lru = "0.16.0"
rand = "0.9.2"
rodio = "0.21.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_yaml = "0.9.33"
