[target.x86_64-unknown-linux-gnu]
pre-build = [
    "apt-get update",
    "apt-get install -y libasound2-dev"
]

[target.aarch64-unknown-linux-gnu]
pre-build = [
    "apt-get update",
    "apt-get install -y libasound2-dev"
]

[target.armv7-unknown-linux-gnueabihf]
pre-build = [
    "apt-get update",
    "apt-get install -y libasound2-dev"
]

[target.i686-unknown-linux-gnu]
pre-build = [
    "apt-get update",
    "apt-get install -y libasound2-dev"
]

[target.s390x-unknown-linux-gnu]
pre-build = [
    "apt-get update",
    "apt-get install -y libasound2-dev"
]

[target.powerpc64-unknown-linux-gnu]
pre-build = [
    "apt-get update",
    "apt-get install -y libasound2-dev"
]

[target.riscv64gc-unknown-linux-gnu]
pre-build = [
    "apt-get update",
    "apt-get install -y libasound2-dev"
]
