on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install alsa libs for rodio
        run: apt-get install alsa-lib-dev

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy

      - name: Rust dependencies cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      
      - name: Run unit tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features

      - name: Check clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-features
  